// // class CartPage {
// //   constructor(page) {
// //     this.page = page;
// //   }

// //   async goToCart() {
// //     await this.page.goto('http://127.0.0.1:5500/website/cart.html'); // FIXED PATH
// //   }
// // }

// // module.exports = CartPage;
// // pages/CartPage.js
// class CartPage {
//   constructor(page) {
//     this.page = page;
//     this.cartItems = '#cart-items';
//     this.cartEmpty = '#cart-empty';
//     this.checkoutBtn = 'button:has-text("Checkout")';
//   }

//   async goToCart() {
//     await this.page.goto('http://127.0.0.1:5500/website/cart.html');
//     await this.page.waitForSelector(this.cartItems + ', ' + this.cartEmpty, { timeout: 10000 });
//   }

//   async isCartEmpty() {
//     return await this.page.isVisible(this.cartEmpty);
//   }

//   async getCartItemCount() {
//     return await this.page.locator(this.cartItems + ' .cart-item').count();
//   }

//   async clickCheckout() {
//     await this.page.click(this.checkoutBtn);
//   }
// }

// module.exports = CartPage;

class CartPage {
  constructor(page) {
    this.page = page;
    this.cartItems = '#cart-items';
    this.emptyMsg = '#cart-empty';
    this.checkoutBtn = '.checkout-btn'; // This is generated by cart.js
  }

  async goto() {
    await this.page.goto('/cart.html');
  }
}
module.exports = CartPage;